import { chromium } from 'playwright';
import { chromiumPath } from '/home/user/laxgame/scripts/chromium.mjs';
const SHOT='/tmp/claude-0/-home-user-laxgame/3fb48e6a-67d8-5fb9-b0aa-0211083b6a02/scratchpad/shots';
const b = await chromium.launch({ executablePath: chromiumPath() });
const ctx = await b.newContext({ viewport:{width:1280,height:800} });
const p = await ctx.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('console',m=>{if(m.type()==='error')errs.push('con:'+m.text())});
await p.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'});
await p.evaluate(()=>localStorage.clear()); await p.reload({waitUntil:'networkidle'});
await p.getByText('Press Start').click(); await p.waitForTimeout(300);
await p.locator('.menu-btn__label').filter({hasText:'Play Now'}).first().click(); await p.waitForTimeout(300);
await p.getByRole('button',{name:'Faceoff'}).click(); await p.waitForTimeout(900);
await p.screenshot({path:`${SHOT}/g1-pregame.png`});
await p.waitForTimeout(3600);
await p.screenshot({path:`${SHOT}/g2-field.png`});
await p.waitForTimeout(3000);
await p.screenshot({path:`${SHOT}/g3-live.png`});
console.log('ERRORS:',JSON.stringify(errs.slice(0,5)));
await b.close();
