import { chromium } from 'playwright';
import { chromiumPath } from './scripts/chromium.mjs';
const SHOT='/tmp/claude-0/-home-user-laxgame/3fb48e6a-67d8-5fb9-b0aa-0211083b6a02/scratchpad/shots';
const b = await chromium.launch({ executablePath: chromiumPath() });
const ctx = await b.newContext({ viewport:{width:1280,height:800} });
const p = await ctx.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'});
await p.evaluate(()=>localStorage.clear()); await p.reload({waitUntil:'networkidle'});
await p.getByText('Press Start').click(); await p.waitForTimeout(300);
await p.locator('.menu-btn__label').filter({hasText:'Play Now'}).first().click(); await p.waitForTimeout(300);
await p.getByRole('button',{name:'Faceoff'}).click(); await p.waitForTimeout(4200);
// Drive the camera to a sideline and to an end line so the venue shows.
await p.evaluate(()=>{ const g=window.loneStarLax; g.match.phase='pregame'; g.match.ball.carrier=null; g.match.ball.x=55; g.match.ball.y=1.5; g.match.focus={x:55,y:1.5}; g.renderer.cam.snap(55,1.5); });
await p.waitForTimeout(600); await p.screenshot({path:`${SHOT}/v-sideline.png`});
await p.evaluate(()=>{ const g=window.loneStarLax; g.match.ball.x=55; g.match.ball.y=58.5; g.match.focus={x:55,y:58.5}; g.renderer.cam.snap(55,58.5); });
await p.waitForTimeout(600); await p.screenshot({path:`${SHOT}/v-benchside.png`});
await p.evaluate(()=>{ const g=window.loneStarLax; g.match.ball.x=3; g.match.ball.y=30; g.match.focus={x:3,y:30}; g.renderer.cam.snap(3,30); });
await p.waitForTimeout(600); await p.screenshot({path:`${SHOT}/v-endline.png`});
console.log('ERRORS:',JSON.stringify(errs.slice(0,3)));
await b.close();
